[project]
name = "langgragh-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lrbwhite", email = "3523395067@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dashscope>=1.0",
    "grandalf>=0.8",
    "httpx>=0.27",
    "langchain>=1.2,<2",
    "langchain-community>=0.3,<1",
    "langchain-core>=1.2,<2",
    "langchain-deepseek>=0.1",
    "langchain-ollama>=0.2",
    "langchain-openai>=1.1,<2",
    "langgraph>=1.0,<2",
    "langgraph-checkpoint-sqlite>=2.0,<4",
    "langgraph-supervisor>=0.0.20,<1",
    "loguru>=0.7.3",
    "openai>=1.0,<3",
    "pydantic>=2.7,<3",
    "python-dotenv>=1.0",
]

[project.scripts]
langgragh-learn = "langgragh_learn:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
