[project]
name = "langgragh-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lrbwhite", email = "3523395067@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langgraph>=1.0,<2",
    "langgraph-checkpoint-sqlite>=2.0,<4",
    "langgraph-supervisor>=0.0.20,<1",
]

[project.scripts]
langgragh-learn = "langgragh_learn:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
